RecordStore_MVC/Models/Album.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RecordStore_MVC.Models
{
    public class Album
    {
        public int Id { get; set; }
        public int BandId { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public string ReleaseDate { get; set; }

        public virtual Band Band { get; set; }

    }


}

RecordStore_MVC/Models/Band.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace RecordStore_MVC.Models
{
    public class Band
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Hometown { get; set; }
        public virtual ICollection<Album> Albums { get; set; }
    }

    public class BandContext : DbContext
    {
        public DbSet<Band> Bands { get; set; }
        public DbSet<Album> Albums { get; set; }
    }
}

RecordStore_MVC/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RecordStore_MVC.Models;

namespace RecordStore_MVC.Controllers
{
    public class AlbumController : Controller
    {
        private BandContext db = new BandContext();

        // GET: Album
        public ActionResult Index()
        {
            var albums = db.Albums.Include(a => a.Band);
            return View(albums.ToList());
        }

        // GET: Album/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // GET: Album/Create
        public ActionResult Create()
        {
            ViewBag.BandId = new SelectList(db.Bands, "Id", "Name");
            return View();
        }

        // POST: Album/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,BandId,Title,Genre,ReleaseDate")] Album album)
        {
            if (ModelState.IsValid)
            {
                db.Albums.Add(album);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BandId = new SelectList(db.Bands, "Id", "Name", album.BandId);
            return View(album);
        }

        // GET: Album/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            ViewBag.BandId = new SelectList(db.Bands, "Id", "Name", album.BandId);
            return View(album);
        }

        // POST: Album/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,BandId,Title,Genre,ReleaseDate")] Album album)
        {
            if (ModelState.IsValid)
            {
                db.Entry(album).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BandId = new SelectList(db.Bands, "Id", "Name", album.BandId);
            return View(album);
        }

        // GET: Album/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Album album = db.Albums.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }
            return View(album);
        }

        // POST: Album/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Album album = db.Albums.Find(id);
            db.Albums.Remove(album);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RecordStore_MVC/Controllers/BandController.cs
using RecordStore_MVC.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RecordStore_MVC.Controllers
{
    public class BandController : Controller
    {

        BandContext db = new BandContext();
        //ICollection<Band> searchResults;
        //[HttpPost]
        /*public ICollection<Band> Index()
            searchResults = db.Bands.ToList();
            return View();
        }
        */
        // GET: Band
        public ActionResult Index()
        {
            ViewBag.bands = db.Bands.ToList();
            /*if (!String.IsNullOrEmpty(search))
            {

                var results = db.Bands.Where(s => s.Name.Contains(search));
                return View(results);
            }
            else
            {*/
                return View();
           // }
              
        }

        public ActionResult Create()
        {
            
            return View();
        }

        [HttpPost]
        public ActionResult Create(Band band)
        {
           
                db.Bands.Add(band);
                db.SaveChanges();
          
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int? Id)
        {
            Band band = db.Bands.Find(Id);
            return View(band);
        }

        [HttpPost]
        public ActionResult Delete(Band band)
        {
            db.Entry(band).State = EntityState.Modified;
            db.Bands.Remove(band);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int? id)
        {
            Band band = db.Bands.Find(id);
            return View(band);            
        }

        [HttpPost]
        public ActionResult Edit(Band band)
        {
                     
            db.Entry(band).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int? Id)
        {
            Band band = db.Bands.Find(Id);
            return View(band);
        }

    }
}

    

RecordStore_MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RecordStore_MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

RecordStore_MVC/Views/Album/Create.cshtml
@model RecordStore_MVC.Models.Album

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.BandId, "BandId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BandId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BandId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RecordStore_MVC/Views/Album/Delete.cshtml
@model RecordStore_MVC.Models.Album

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Band.Name)
            
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Band.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RecordStore_MVC/Views/Album/Details.cshtml
@model RecordStore_MVC.Models.Album

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Album</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Band.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Band.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

RecordStore_MVC/Views/Album/Edit.cshtml
@model RecordStore_MVC.Models.Album

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.BandId, "BandId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BandId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BandId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RecordStore_MVC/Views/Album/Index.cshtml
@model IEnumerable<RecordStore_MVC.Models.Album>

@{
    ViewBag.Title = "Albums";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create Album", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Band.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Band.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Genre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReleaseDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

RecordStore_MVC/Views/Band/Create.cshtml
@model RecordStore_MVC.Models.Band

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Band"))
{
    <p>
        @Html.TextBox("Name", null, new { @class = "form-control", placeholder = "Band Name" })
    </p>
    <p>
        @Html.TextBox("Hometown", null, new { @class = "form-control", placeholder = "Band Hometown" })
    </p>
    <p>
        <input type="submit" class="btn btn-default" value="Create Band" />
    </p>
}

    

        

RecordStore_MVC/Views/Band/Delete.cshtml
@model RecordStore_MVC.Models.Band
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
<h3>Are you sure you want to delete this?</h3>
<h4>Band</h4>
    <hr />
<table>
    <tr>
        <td>
            @Html.DisplayFor(model => model.Name)
        </td>
    </tr>
    
        <tr>
            <td>
                -from-
            </td>
        </tr>
    <tr>
        <td>
            @Html.DisplayFor(model => model.Hometown)
        </td>
    </tr>
</table>
<hr/>
@using (Html.BeginForm())
{

    <div class="form-actions">
        <input type="submit" class="btn btn-default" value="Delete" /> |
        @Html.ActionLink("Cancel", "Index")
    </div>
}

RecordStore_MVC/Views/Band/Details.cshtml
@model RecordStore_MVC.Models.Band
@{
    ViewBag.Title = "Details";
}
<h4>Band</h4>
<h2>Details</h2>

<table>
    <tr>
        <td>
            @Html.DisplayFor(model => model.Name)
        </td>
    </tr>

    <tr>
        <td>
            -from-
        </td>
    </tr>
    <tr>
        <td>
            @Html.DisplayFor(model => model.Hometown)
        </td>
    </tr>
</table>

RecordStore_MVC/Views/Band/Edit.cshtml
@model RecordStore_MVC.Models.Band
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
    <h4>Album</h4>
    <hr />
    
   @using (Html.BeginForm("Edit", "Band"))
   {
    <p>
        @Html.TextBox("Name", null, new { @class = "form-control"})
    </p>
    <p>
        @Html.TextBox("id", null, new { @class = "form-control hidden"})
    </p>
    <p>
        @Html.TextBox("Hometown", null, new { @class = "form-control"})
    </p>
    <p>
        <input type="submit" class="btn btn-default" value="Edit Band" />
    </p>
    <p>
        @Html.ActionLink("Cancel", "Index")
    </p>
    
   }


   
            
        
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

RecordStore_MVC/Views/Band/index.cshtml
@{
    ViewBag.PageTitle = "Band";
}

<h2>Band List</h2>

    <table class="table">
        <thead>
            <tr>
                <th>Band</th>
                <th>Hometown</th>               
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var band in ViewBag.bands)
            {
            <tr>
                <td>
                    @band.Name
                </td>
                <td>
                    @band.Hometown
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = band.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = band.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = band.Id })
                </td>
            </tr>
            }
            
        </tbody>
    </table>

RecordStore_MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}



<div class="row">
    <div class="col-md-4">
        
        
    </div>
    <div class="col-md-4">
        
    </div>
    <div class="col-md-4">
       
    </div>
</div>

RecordStore_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Record Store</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Record Store", "Index", "Band", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Bands", "Index", "Band")</li>
                    <li>@Html.ActionLink("Albums", "Index", "Album")</li>                  
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Record Store App</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>